CREATE TABLE IF NOT EXISTS WRESTLER (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255)
);
ALTER TABLE WRESTLER ALTER COLUMN id RESTART WITH 1;

